# Generated by Django 5.0.1 on 2024-02-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_recurrence', models.PositiveSmallIntegerField()),
                ('max_regime', models.PositiveSmallIntegerField()),
                ('max_box_variety', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('live_plants_percent_regime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sequence_number', models.IntegerField(null=True)),
                ('is_templated', models.BooleanField(default=False)),
                ('sequence_box_number', models.PositiveSmallIntegerField()),
                ('relative_template_percent', models.FloatField()),
                ('score', models.PositiveSmallIntegerField()),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('recurrence', models.PositiveSmallIntegerField()),
                ('all_plants', models.PositiveSmallIntegerField()),
                ('live_plants', models.PositiveSmallIntegerField()),
                ('grown_plants_value', models.PositiveSmallIntegerField()),
                ('live_plants_percent', models.FloatField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experimentAPI.box')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experimentAPI.experiment')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experimentAPI.regime')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experimentAPI.variety')),
            ],
        ),
    ]
