# Generated by Django 5.0.1 on 2024-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvalues',
            name='regime',
        ),
        migrations.RemoveField(
            model_name='currentvalues',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='experiment',
            name='start_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Regime',
        ),
    ]
