# Generated by Django 5.0.1 on 2024-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0005_alter_variety_relative_template_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='sequence_box_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
