# Generated by Django 5.0.1 on 2024-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0006_alter_variety_sequence_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='sequence_box_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='variety',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
    ]
