# Generated by Django 5.0.1 on 2024-02-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0007_alter_variety_sequence_box_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvalues',
            name='grown_plants_value',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
