# Generated by Django 5.0.1 on 2024-02-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0008_alter_currentvalues_grown_plants_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentvalues',
            old_name='box',
            new_name='box_id',
        ),
        migrations.RenameField(
            model_name='currentvalues',
            old_name='experiment',
            new_name='experiment_id',
        ),
        migrations.RenameField(
            model_name='currentvalues',
            old_name='variety',
            new_name='variety_id',
        ),
    ]
