# Generated by Django 5.0.1 on 2024-02-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0010_rename_box_id_currentvalues_referring_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentvalues',
            old_name='referring_box',
            new_name='box_id',
        ),
        migrations.RenameField(
            model_name='currentvalues',
            old_name='referring_experiment',
            new_name='experiment_id',
        ),
        migrations.RenameField(
            model_name='currentvalues',
            old_name='referring_variety',
            new_name='variety_id',
        ),
    ]
