# Generated by Django 5.0.1 on 2024-02-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentAPI', '0011_rename_referring_box_currentvalues_box_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvalues',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='experimentAPI.box'),
        ),
    ]
